apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-dev-pv
  labels:
    app: media-server-dev-pv
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
spec:
  capacity:
    storage: 50Gi
  nfs:
    server: 10.10.150.111
    path: /opt/storage/media-server-dev
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.0
    - retrans=10
  volumeMode: Filesystem
