apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-dev-pvc
  namespace: dev
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: media-server-dev-pv
  storageClassName: ''
  volumeMode: Filesystem
