apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-prod-pvc
  namespace: prod
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: media-server-prod-pv
  storageClassName: ''
  volumeMode: Filesystem
